name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check for package.json
      id: check_package
      run: |
        if [ ! -f "package.json" ]; then
          echo "❌ package.json not found. Skipping build."
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "✅ package.json found."
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Install Dependencies
      if: steps.check_package.outputs.skip == 'false'
      run: npm ci

    - name: Run Grunt Tasks
      if: steps.check_package.outputs.skip == 'false'
      run: npx grunt
